apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: wordpress-stream
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 'docker.io/marcusandersson99/wordpress:latest'
    importPolicy:
      importMode: Legacy
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
